### ISSUE TITLE
Revisión

### ISSUE THREAD

**Issue by EduardoHernandezGuzman** [4GeeksAcademy/Alejandro-Trave-Todo-Fetch-Crud#1]
# Revisión - Hacen falta unos cambios ⚠️

## Feedback
- Buen trabajo @Atravep 😁 ... no está implementada la funcionalidad de editar tareas (método PUT)

## Estilo de código y limpieza
- Código limpio y bien estructurado.

## Mejores prácticas/comentarios
- Te invito a que añadas la funcionalidad de crear un nuevo usuario

**Comment by Atravep** [comment]
Hola, Edu!. Entiendo que esto es para que meta los extras, verdad? No vi estas tareas extra en la página de la actividad de 4 Geeks. O se me han pasado!!🤦‍♂️

**Comment by Atravep** [comment]
Discúlpame, me confundí de texto descriptivo de la tarea y me faltó la edición.

**Comment by EduardoHernandezGuzman** [comment]
Muy buen trabajo Alejandro.
